name: CI  
on:  
  push:  
    branches: [ master ]  
  pull_request:  
    branches: [ master ]  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
      - name: Set up Docker  
        uses: docker/setup-docker@v1  
      - name: Build image  
        run: docker build -t idcims/gemini_express_api:latest .  
      - name: Push image to registry  
        run: docker push idcims/gemini_express_api:latest
